# Quarkus Configuration
quarkus.http.port=8080

# REST Client Configurations
quarkus.rest-client.user-client.url=http://localhost:8081
quarkus.rest-client.product-client.url=http://localhost:8082
quarkus.rest-client.order-client.url=http://localhost:8083

# Jackson Configuration
quarkus.jackson.fail-on-empty-beans=false
