# Quarkus Configuration
quarkus.http.port=8080
quarkus.resteasy-reactive.path=/esb
# CORS Configuration
quarkus.http.cors=true
quarkus.http.cors.origins=*
quarkus.http.cors.methods=GET,PUT,POST,DELETE,PATCH,OPTIONS
quarkus.http.cors.headers=accept, authorization, content-type, x-requested-with
quarkus.http.cors.access-control-allow-credentials=false

# Database Configuration
quarkus.datasource.db-kind=mysql
quarkus.datasource.jdbc.url=jdbc:mysql://localhost:3306/cafe?createDatabaseIfNotExist=true
quarkus.datasource.username=root
quarkus.datasource.password=123456

# Hibernate Configuration
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true

# JWT Security
quarkus.smallrye-jwt.enabled=true
mp.jwt.verify.issuer=http://localhost:8080
mp.jwt.verify.publickey.location=publicKey.pem
smallrye.jwt.sign.key.location=privateKey.pem
smallrye.jwt.verify.publickey.location=publicKey.pem
quarkus.smallrye-jwt.path.groups=groups

# Jackson Configuration
quarkus.jackson.fail-on-empty-beans=false

# Swagger UI
quarkus.swagger-ui.always-include=true

# Logging
quarkus.log.level=INFO
quarkus.log.category."com.example.cafe".level=DEBUG
