# Quarkus Configuration
quarkus.http.port=8083

# Database Configuration
quarkus.datasource.db-kind=mysql
quarkus.datasource.jdbc.url=jdbc:mysql://localhost:3306/cafe
quarkus.datasource.username=root
quarkus.datasource.password=123456

# Hibernate Configuration
quarkus.hibernate-orm.database.generation=update

# JWT Security
quarkus.smallrye-jwt.enabled=true
mp.jwt.verify.issuer=http://localhost:8080
quarkus.smallrye-jwt.path.groups=scope

# REST Client Configuration
# The name "product-client" should match the @RegisterRestClient(configKey = "product-client")
quarkus.rest-client.product-client.url=http://localhost:8082
