quarkus.datasource.db-kind=mysql
quarkus.datasource.jdbc.url=jdbc:mysql://localhost:3306/cafe
quarkus.datasource.username=root
quarkus.datasource.password=123456

# JPA / Hibernate
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.physical-naming-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

quarkus.http.port=8081

# JWT verification (HS512)
smallrye.jwt.verify.key.algorithm=HS512
mp.jwt.verify.publickey=8VG09PFX0cgB8QSoHL4Tr6Ga6iplAmlulN8Xhi0J8aKpV706sf25auETOHWA2dZy
security.jwt.secret=8VG09PFX0cgB8QSoHL4Tr6Ga6iplAmlulN8Xhi0J8aKpV706sf25auETOHWA2dZy
